version: '3'

services:
  web:
    build: .
    image: maxcoldrick/foodapi
    volumes:
       - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    # environment:
    #   DATABASE_URL: dbformcfoodapi.postgres.database.azure.com
  # db:
  #   image: postgres:10.3-alpine
  # java:
  #   build: databaseFillerUpper/
  #   image: maxcoldrick/fillerupper
  #   links:
  #     - web
  #   depends_on:
  #     - web
