version: '3'

services:
  web:
    build: .
    image: maxcoldrick/foodapi
    entrypoint: migrate/dbmigrate.sh
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
    ports:
      - 5432:5432
  java:
    build: databaseFillerUpper/
    image: maxcoldrick/databasefillerupper
    links:
      - web
    depends_on:
      - web
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
  server:
    build: nginx/
    image: maxcoldrick/foodapi_nginx
    ports:
      - 80:80
      - 443:443
