apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: java
  name: java
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: java
    spec:
      containers:
      - image: maxcoldrick/databasefillerupper
        name: java
        resources: {}
      restartPolicy: Always
status: {}
