source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 5.2.3'

gem 'pg', '>= 0.18', '< 2.0'

gem 'puma', '~> 3.12'

gem "bunny", ">= 2.9.2"

gem 'listen', '~> 3.1.5'

gem 'devise_token_auth'

gem 'bcrypt', '~> 3.1.7'

gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
